name: CI

on:
  pull_request:

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run black
        run: black --check src tests

      - name: Run isort
        run: isort --check-only src tests

      - name: Run flake8
        run: flake8 src tests

      - name: Run mypy
        run: mypy src

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest==7.0.1

      - name: Run pytest
        run: pytest tests
