name: CI

on:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black==21.12b0 flake8==4.0.1 flake8-bugbear==22.1.11 \
                      flake8-pie==0.15.0 isort==5.9.3 mypy==0.931 pytest==7.0.1

      - name: Run Black
        run: black --check src tests

      - name: Run isort
        run: isort --check-only src tests

      - name: Run flake8
        run: flake8 src tests

      - name: Run mypy
        run: mypy src

      - name: Run pytest
        run: pytest
        continue-on-error: true
