name: Python CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest mypy black isort flake8

      - name: Run all checks
        run: |
          set +e
          FAIL=0

          echo "=== Running pytest ==="
          pytest tests || FAIL=1

          echo "=== Running mypy ==="
          mypy src/ || FAIL=1

          echo "=== Running black ==="
          black --diff --check src/ || FAIL=1

          echo "=== Running isort ==="
          isort --check-only src/ || FAIL=1

          echo "=== Running flake8 ==="
          flake8 src/ || FAIL=1

          exit $FAIL
